# Generated by Django 3.0 on 2019-12-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(default='Yeet', max_length=50, verbose_name='Event Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='Yah', max_length=200, unique=True, verbose_name='Event Title'),
            preserve_default=False,
        ),
    ]
